#datasource 配置数据源
spring:
    datasource:
        url: jdbc:mysql://localhost:3305/wcsy?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: 321
        driver-class-name: com.mysql.jdbc.Driver







