#datasource 配置数据源
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/wcsy?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver







